run1: ex1
	./ex1

run2: ex2
	./ex2

run3: ex3
	./ex3

ex1: ex1.cpp
	g++ -o ex1 ex1.cpp

ex2: ex2.cpp
	g++ -o ex2 ex2.cpp

ex3: ex3.cpp
	g++ -o ex3 ex3.cpp

delete:
	rm -f ex1
	rm -f ex2
	rm -f ex3
